### ISSUE TITLE
[ENH] Make logging configurable

### ISSUE THREAD

**Issue by PBXg33k** [Sn0wCrack/ExHentai-Archive#14]
I'd like to propose to replace the current logging implementation with https://seldaek.github.io/monolog/.

Reason for this is that monolog is a widely supporting logging library with support of many handlers, and many other things.
In my case, running in docker, i want to log to either file, console output and/or a remote logging server.

The easiest implementation for now would be in my opinion:
- [ ] Add composer.json and monolog to project.
- [ ] In current log calls, call the respective monolog log call
- [ ] Deprecate current log calls
- [ ] Update all reference to old log methods
- [ ] Update install/usage guide as this adds composer as a package manager dependency

Optional:
- [ ] Update config logic to make logging configurable via config.json (i personally don't recommend this)

**Comment by Sn0wCrack** [comment]
I don't particular think this is something I'm going to support with ExHentai-Archive unfortunately.

I'm mostly just updating ExHentai-Archive when things absolutely munt themselves because of changes to e-hentai.

I'm currently working on a replacement to ExHentai-Archive called [SadPanda-Archive](https://github.com/Sn0wCrack/SadPanda-Archive) that I'm focusing on right now.

It should hopefully be a drop in replacement in some regards (I'll probably write up a upgrade guide once things are fully up and running), and improvements in others. I'm definitely focusing on logging as one of the improvements I'm going to make (and already having using Winston and Morgan for the server-side logging).
